### PR TITLE
Handling wrong id exception

### LINKED ISSUE #51: Add basic tests for PharmacyController

### LINKED ISSUE #90: Add id_not_found exception and handle it.
Delete methods get 500 code when I try to delete an object by not existing id.

### PR DESCRIPTION
**Pull request by MuchosChuchos**
Add new custom exception.
Add handling api exceptions.
Handle invalid id exception in controllers
 in delete, update and getById methods.

Fix #90  
Closes #51

### CODE REVIEW

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    }
+
+    public InvalidIdentifierException(Long pharmacyId, Long medicineId) {
+        super("Invalid Price id: medicine_id: " + medicineId + "; pharmacy_id: " + pharmacyId + ".");
+    }
+
+    public InvalidIdentifierException() {
+        super("Invalid id.");
+    }
+}
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java:20]: Add a new line here

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+import org.springframework.web.bind.annotation.ControllerAdvice;
+import org.springframework.web.bind.annotation.ExceptionHandler;
+import org.springframework.web.context.request.WebRequest;
+import org.springframework.web.server.ResponseStatusException;
+
+@ControllerAdvice
+public class RestExceptionHandler {
+
+    @ExceptionHandler(ResponseStatusException.class)
+    protected ResponseEntity<Object> handleException(ResponseStatusException ex, WebRequest request) {
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:14]: Why is it protected?
Why `ResponseEntity<Object>` if it is always `ResponseEntity<ApiError>`

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java (hunk 1 above)
Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java:20]: Done

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+@ResponseStatus(HttpStatus.NOT_FOUND)
+public class InvalidIdentifierException extends RuntimeException {
+
+    public InvalidIdentifierException(Long id) {
+        super("Invalid id: " + id + ".");
+    }
+
+    public InvalidIdentifierException(Long pharmacyId, Long medicineId) {
+        super("Invalid Price id: medicine_id: " + medicineId + "; pharmacy_id: " + pharmacyId + ".");
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java:14]: `String#format`

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java [hunk 4]
```diff
@@ -0,0 +1,20 @@
+package com.eleks.academy.pharmagator.exceptions;
+
+import org.springframework.http.HttpStatus;
+import org.springframework.web.bind.annotation.ResponseStatus;
+
+@ResponseStatus(HttpStatus.NOT_FOUND)
+public class InvalidIdentifierException extends RuntimeException {
+
+    public InvalidIdentifierException(Long id) {
+        super("Invalid id: " + id + ".");
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java:10]: Trailing dot is redundant in api messages

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java [hunk 5]
```diff
@@ -0,0 +1,20 @@
+package com.eleks.academy.pharmagator.exceptions;
+
+import org.springframework.http.HttpStatus;
+import org.springframework.web.bind.annotation.ResponseStatus;
+
+@ResponseStatus(HttpStatus.NOT_FOUND)
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java:6]: Why do you need it here?
You already handle this exception in `RestExceptionHandler#handleException(InvalidIdentifierException, WebRequest)` with a corresponding status code.

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java (hunk 2 above)
Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:14]: Protected was in an example. And I can say the same about ResponseEntity<Object>. I agree it is always ResponseEntity<ApiError>

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java (hunk 4 above)
Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/InvalidIdentifierException.java:10]: ok

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java [hunk 6]
```diff
@@ -0,0 +1,24 @@
+package com.eleks.academy.pharmagator.exceptions;
+
+import org.springframework.http.HttpStatus;
+import org.springframework.http.ResponseEntity;
+import org.springframework.web.bind.annotation.ControllerAdvice;
+import org.springframework.web.bind.annotation.ExceptionHandler;
+import org.springframework.web.context.request.WebRequest;
+import org.springframework.web.server.ResponseStatusException;
+
+@ControllerAdvice
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:10]: Semantically `@RestControllerAdvice` is more applicable here.

File: api/src/main/java/com/eleks/academy/pharmagator/services/MedicineServiceImpl.java [hunk 7]
```diff
@@ -44,7 +45,8 @@ public Medicine save(MedicineDto medicineDto) {
     }
 
     public void delete(Long id) {
-        medicineRepository.deleteById(id);
+        Medicine medicine = medicineRepository.findById(id).orElseThrow(() -> new InvalidIdentifierException(id));
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/services/MedicineServiceImpl.java:48]: You perform a whole additiona DBl call to simply check whether the record exists???

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+public class RestExceptionHandler {
+
+    @ExceptionHandler(ResponseStatusException.class)
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:13]: Interesting approach, taking into account the fact that `ResponseStatusException` is already beeing handled by Spring itself. Just wondering why you decided to re-handle it by yourself?

Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:13]: To simplify json in response

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+    protected ResponseEntity<Object> handleException(ResponseStatusException ex, WebRequest request) {
+        ApiError apiError = new ApiError(ex.getReason());
+        return new ResponseEntity<>(apiError, ex.getStatus());
+    }
+
+    @ExceptionHandler(InvalidIdentifierException.class)
+    protected ResponseEntity<Object> handleException(InvalidIdentifierException ex, WebRequest request) {
+        ApiError apiError = new ApiError(ex.getMessage());
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:21]: Not a complaint, leave it be, by I don't find this reference necessary in 2-lines method.

File: api/src/main/java/com/eleks/academy/pharmagator/services/MedicineServiceImpl.java (hunk 7 above)
Comment (sergvasylchak) [reply api/src/main/java/com/eleks/academy/pharmagator/services/MedicineServiceImpl.java:48]: If you'd wanna apply the 404 mechanism for delete you should have had a look at `@Modifying` delete query in `JpaRepository<T, ID>` - there is a possibility to return an **int = number of rows updated(deleted)** which you could later check for equality to zero.

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java (hunk 2 above)
Comment (sergvasylchak) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:14]: Leave protected if you like, but remove the unnecessary generification to `Object`. `ResponseEntity<Object>` -> `ResponseEntity<ApiError`.

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java (hunk 8 above)
Comment (sergvasylchak) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:13]: That's fair, leave it be

**Comment by sergvasylchak** [comment]
Even though I find the PR quality satisfactory, I wonder if there is a real need to expose the identifiers existence data in response.
I find it quite vulnerable to show messages like `Record with id %d does not exist` (and/or expose 404 status) as we become much easier to be brute forced.

For example, delete request does not have any request body and therefore is not being validated. Having the trivial script written I will be able to locate the id ranges as far as I receive first non-404 response.
In previous approach there was always 204 response and therefore all of the brute force attack would be blind to actually tell whether anything is beeing executed on the service.

**P.S.** This is not crutial here, because we do expose GET "/{resource}" where all of the identifiers are visible, but it's a nice topic to think about in terms of sensitive data exposure.

@Oleksandr-Eleks please take a glance at this PR.

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java (hunk 2 above)
Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:14]: yep

File: api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java (hunk 9 above)
Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/exceptions/RestExceptionHandler.java:21]: done

File: api/src/main/java/com/eleks/academy/pharmagator/services/MedicineServiceImpl.java (hunk 7 above)
Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/services/MedicineServiceImpl.java:48]: I will leave it be, as it was because the DELETE method is idempotent and the 404 mechanism brokes that.

Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/services/MedicineServiceImpl.java:48]: Anyway, if I'll implement your approach, whether the app will not throw org.springframework.dao.EmptyResultDataAccessException: No class {class location} entity with id {id} exists!

File: api/src/main/java/com/eleks/academy/pharmagator/services/PriceServiceImpl.java [hunk 10]
```diff
@@ -51,7 +50,11 @@
     @Override
     public void deleteById(Long pharmacyId, Long medicineId) {
         PriceId priceId = new PriceId(pharmacyId, medicineId);
-        priceRepository.deleteById(priceId);
+        try {
+            priceRepository.deleteById(priceId);
+        } catch (EmptyResultDataAccessException exception) {
+            log.info(exception.getMessage(), exception);
```
Comment (sergvasylchak) [inline api/src/main/java/com/eleks/academy/pharmagator/services/PriceServiceImpl.java:56]: Is this exception actually ever thrown from `CrudRepository#deleteById`?

Comment (MuchosChuchos) [reply api/src/main/java/com/eleks/academy/pharmagator/services/PriceServiceImpl.java:56]: Yes, [exception stack trace](https://imgur.com/vx19opG)

**Comment by kolyaratishin** [comment]
I advise you to rebase, because in your PR there are many changes that are already present in the develop branch. So, there are some inconsistencies

**Comment by MuchosChuchos** [comment]
> I advise you to rebase because in your PR there are many changes that are already present in the develop branch. So, there are some inconsistencies

I'm thinking about this problem. I want to remove changes that are not mine.

P.S. I have already done rebase, but I have made a mistake when I push a new commit after rebasing. I should use "force-push", but I'm late

**Comment by kolyaratishin** [comment]
You can still do a rebase) Or as a last resort, you can do a reset --hard and rewrite your code)

**Comment by MuchosChuchos** [comment]
> You can still do a rebase) Or as a last resort, you can do a reset --hard and rewrite your code)
@kolyaratishin 
Actually no. Re-calling rebase won't affect the current branch. You can call rebase as much as you can, however, it would be the same result. 

P.S. I've already fixed this problem and "-i rebase" helps me.

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java [hunk 11]
```diff
@@ -0,0 +1,182 @@
...
+        mockMvc.perform(MockMvcRequestBuilders.get(BASE_URI + "/112").accept(MediaType.APPLICATION_JSON))
+                .andExpect(status().isNotFound())
+                .andDo(print());
+    }
+
+    @Test
+    void create_ok() throws Exception {
+        doReturn(pharmacy).when(pharmacyService).save(modelMapper.map(pharmacy, PharmacyDto.class));
+
+        mockMvc
```
Comment (Oleksandr-Eleks) [inline api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java:98]: Please inline

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java [hunk 12]
```diff
@@ -0,0 +1,182 @@
...
+                .andExpect(jsonPath("$.name").value(pharmacy.getName()))
+                .andExpect(jsonPath("$.medicineLinkTemplate").value(pharmacy.getMedicineLinkTemplate()))
+                .andDo(print());
+    }
+
+    @Test
+    void create_invalidRequestBody_400Code() throws Exception {
+        doReturn(pharmacy).when(pharmacyService).save(modelMapper.map(pharmacy, PharmacyDto.class));
+
+        mockMvc
```
Comment (Oleksandr-Eleks) [inline api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java:115]: Inline

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java [hunk 13]
```diff
@@ -0,0 +1,182 @@
...
+                        .accept(MediaType.APPLICATION_JSON))
+                .andExpect(status().isBadRequest())
+                .andDo(print());
+    }
+
+    @Test
+    void update_ok() throws Exception {
+        doReturn(Optional.of(pharmacy)).when(pharmacyService).update(pharmacy.getId(), modelMapper.map(pharmacy, PharmacyDto.class));
+
+        mockMvc
```
Comment (Oleksandr-Eleks) [inline api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java:133]: inline

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java [hunk 14]
```diff
@@ -0,0 +1,182 @@
...
+                .andExpect(jsonPath("$.name").value(pharmacy.getName()))
+                .andExpect(jsonPath("$.medicineLinkTemplate").value(pharmacy.getMedicineLinkTemplate()))
+                .andDo(print());
+    }
+
+    @Test
+    void update_invalidRequestBody_400Code() throws Exception {
+        doReturn(Optional.of(pharmacy)).when(pharmacyService).update(pharmacy.getId(), modelMapper.map(pharmacy, PharmacyDto.class));
+
+        mockMvc
```
Comment (Oleksandr-Eleks) [inline api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java:150]: inline

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java (hunk 11 above)
Comment (MuchosChuchos) [reply api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java]: done

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java (hunk 13 above)
Comment (MuchosChuchos) [reply api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java]: yessiir

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java (hunk 12 above)
Comment (MuchosChuchos) [reply api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java]: done

File: api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java (hunk 14 above)
Comment (MuchosChuchos) [reply api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerTest.java]: yep

**Review by Oleksandr-Eleks — APPROVED** [review]

**Review by kolyaratishin — APPROVED** [review]

**Review by MariamnaKh — APPROVED** [review]
